#!/bin/sh
#
# Configuration for shell profile,
# sourced by all shells.

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="$LC_ALL"

# Vim as standard editor
export EDITOR=vim
# hack
export SCREEN_COLORS=256

# Add directory to path (if it exists)
add_to_path()
{
  if [ -d "$1" ] ; then
    export PATH="$1:$PATH"
    return 0
  else
    return 1
  fi
}

# Source shell script (if it exists)
call()
{
  if [ -f "$1" ] ; then
    . "$1"
    return $?
  else
    return 1
  fi
}

# Add bin directories
add_to_path $HOME/.local/bin
add_to_path $HOME/bin
# rvm
add_to_path "$HOME/.rvm/bin" && \
  call "$HOME/.rvm/scripts/rvm"
# android sdk
add_to_path $HOME/.local/share/android-sdk/tools
add_to_path $HOME/.local/share/android-sdk/platform-tools

# Shell aliases
call $HOME/.aliases

# vim: ft=sh et sw=2 sts=2
