# vim: set ft=sh

# Constants
gsa="git submodule add"
dir="Configs/Vim/bundle"

$gsa "https://github.com/tpope/vim-surround.git"            "$dir/surround"
$gsa "https://github.com/mattn/webapi-vim.git"              "$dir/webapi"
$gsa "https://github.com/tpope/vim-repeat.git"              "$dir/repeat"
$gsa "https://github.com/tpope/vim-speeddating.git"         "$dir/speeddating"
$gsa "https://github.com/MarcWeber/vim-addon-mw-utils.git"  "$dir/addon-mw-utils"
$gsa "https://github.com/flazz/vim-colorschemes.git"        "$dir/colorschemes"
$gsa "https://github.com/derekwyatt/vim-fswitch.git"        "$dir/fswitch"
$gsa "https://github.com/tpope/vim-fugitive.git"            "$dir/fugitive"
$gsa "https://github.com/mattn/gist-vim.git"                "$dir/gist"
$gsa "https://github.com/tsaleh/vim-matchit.git"            "$dir/matchit"
$gsa "https://github.com/vim-scripts/taglist.vim.git"       "$dir/taglist"
$gsa "https://github.com/scrooloose/nerdcommenter.git"      "$dir/nerdcommenter"
$gsa "https://github.com/scrooloose/nerdtree.git"           "$dir/nerdtree"
$gsa "https://github.com/vim-scripts/OmniCppComplete.git"   "$dir/OmniCppComplete"
$gsa "https://github.com/ervandew/supertab.git"             "$dir/supertab"
$gsa "https://github.com/vim-scripts/tlib.git"              "$dir/tlib"
$gsa "https://github.com/vim-scripts/VisIncr.git"           "$dir/VisIncr"
$gsa "https://github.com/drmingdrmer/xptemplate.git"        "$dir/xptemplate"
$gsa "https://github.com/wincent/Command-T.git"             "$dir/Command-T"
