" The "m" at the end of Vi
set nocompatible

" Windows / UNIX compatibility
let s:is_windows = (has('win32') || has('win64')) && &shellcmdflag =~ '/'
let s:vim_dir = s:is_windows ? $VIM . '/vimfiles' : $HOME . '/.vim'

let $VIMDIR = s:vim_dir

if s:is_windows
    let $BUNDLE = $USERPROFILE . '/Bundle'
else
    let $BUNDLE = $HOME . '/Bundle'
endif

" Plugins
filetype off
let &runtimepath .= ',' . s:vim_dir . '/bundle/Vundle.vim'
call vundle#begin(s:vim_dir . '/bundle')

Plugin 'VundleVim/Vundle.vim'

" obligatory Tim Pope plugins
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-rsi'
Plugin 'tpope/vim-unimpaired'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-surround'

" window management
"Plugin 'roman/golden-ratio'

" navigation
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'FelikZ/ctrlp-py-matcher'
Plugin 'dietsche/vim-lastplace'
Plugin 'tmhedberg/matchit'
Plugin 'python_match.vim'
Plugin 'mileszs/ack.vim'

" editing
Plugin 'argtextobj.vim'
"Plugin 'chrisbra/NrrwRgn'
Plugin 'christoomey/vim-sort-motion'
Plugin 'idanarye/vim-casetrate'
Plugin 'junegunn/vim-easy-align'

" current colorscheme
"Plugin 'marciomazza/vim-brogrammer-theme'
"Plugin 'w0ng/vim-hybrid'
"Plugin 'altercation/vim-colors-solarized'
Plugin 'wombat256.vim'

" not used often, but better than the default
Plugin 'scrooloose/nerdtree', { 'for': 'NERDTreeToggle' }

" org-mode for Vim
" Plugin 'tpope/vim-speeddating'
" Plugin 'jceb/vim-orgmode'

" xolox, used for various utilities (:Open, parallel commands)
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-shell'

" C++ plugins
Plugin 'octol/vim-cpp-enhanced-highlight'

" Rust plugins
Plugin 'rust-lang/rust.vim'
Plugin 'racer-rust/vim-racer'

" neovim-specific plugins
if has('nvim')
    Plugin 'Shougo/deoplete.nvim'

    let g:deoplete#enable_at_startup = 1

    "Plugin 'autozimu/LanguageClient-neovim'
    "Plugin 'Shougo/echodoc.vim' " optional: function signature and inline doc

    "let g:LanguageClient_serverCommands = {
    "    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    "    \ }

    "let g:LanguageClient_autoStart = 1

    "nmap <silent> <leader>lk :call LanguageClient_textDocument_hover()<cr>
    "nmap <silent> <leader>ld :call LanguageClient_textDocument_definition()<cr>
    "nmap <silent> <leader>lr :call LanguageClient_textDocument_rename()<cr>
endif

call vundle#end()
filetype plugin indent on

" Leader is "<space>"
let mapleader = "\<space>"

" Sets how many lines of history Vim has to remember
set history=1000

" Reload buffer when its file is changed from the outside
set autoread

" Set UTF8 as standard encoding
set encoding=utf8

" Use Unix as the standard file type
set fileformats=unix,dos,mac

" Disable backup/swap
set nobackup
set nowritebackup
set noswapfile

" Add "$" at end of "change" nouns
set cpoptions+=$

" Set extra options when running in GUI mode
if has('gui_running')
    set guitablabel=%M\ %t
    set guioptions-=r
    set guioptions-=R
    set guioptions-=l
    set guioptions-=L
    set guioptions-=m
    set guioptions-=e
    set guioptions-=T
endif

" Remove startup message
set shortmess+=I

" Don't redraw while executing macros (good performance config)
set lazyredraw

" Title is name of current file
set title

" Set amount of lines above the cursor
set scrolloff=3

" Show line numbers, but relative
set number
set relativenumber

" Always show current position
set ruler

" Height of the command bar
set cmdheight=2

" Status line
set statusline=%t                               " tail of the filename
set statusline+=\ %m                            " modified flag
set statusline+=%h                              " help file flag
set statusline+=%r                              " read only flag
set statusline+=%y                              " filetype
set statusline+=[%{strlen(&fenc)?&fenc:'none'}] " file encoding
set statusline+=[%{&ff}]                        " file format
set statusline+=%=                              " left/right separator
set statusline+=%c,                             " cursor column
set statusline+=%l                              " cursor line
set statusline+=\ %P                            " percent through file

" Always put a status line in, even if there is only one window
set laststatus=2

" Turn on the Wild menu
set wildmenu

" Behave shell-like when completing shell
set wildmode=longest,list

" Ignore compiled files and backups
set wildignore=
set wildignore+=*~
set wildignore+=*.o
set wildignore+=*.class
set wildignore+=*.pyc
set wildignore+=*.gch
set wildignore+=*.obj
set wildignore+=*.pdb
set wildignore+=*.lib
set wildignore+=*.arg

" Virtual edit
set virtualedit=
set whichwrap+=<,>,h,l " disabled when virtualedit

" Backspace unindents and joins lines
set backspace=start,indent,eol

" Don't notify any errors
set noerrorbells
set visualbell
set t_vb=
set timeoutlen=500

" Hide the mouse pointer while typing
set mousehide

" Mouse activated
set mouse=a

" Enable syntax highlighting
syntax enable

" Enable modeline
set modeline

" Show matching brackets when text indicator is over them
set showmatch

" How many tenths of a second to blink when matching brackets
set matchtime=2

" Default fold method
set foldmethod=indent

" Max number of fold levels
set foldnestmax=10

" Folding everything (disable at start)
set nofoldenable

" Again, folding parent levels
set foldlevel=1

" Default complete function
set omnifunc=syntaxcomplete#Complete

" Complete menu
set completeopt=menuone,preview

" Use spaces instead of tabs
set expandtab

" Be smart when using tabs
set smarttab

" Indent by 4 spaces/tabs
set shiftwidth=4
set softtabstop=4
set tabstop=4

" Round indent to multiple of tabstop/shiftwidth
set shiftround

" Invisible characters
set list listchars=tab:>-,trail:.,extends:>
set showbreak=>\

" Explicit FTW
set autoindent
set smartindent
set wrap

" Regex magic
set magic

" Ignore case
set ignorecase

" Try to be smart about cases
set smartcase

" Highlight results
set hlsearch

" Makes search act like in modern browsers
set incsearch
set wrapscan

" Colorscheme setup
set background=dark
colorscheme wombat256mod
" set background=light
" colorscheme default
hi Normal ctermbg=none

" GUI font
if has('gui_running')
    if s:is_windows
        set guifont=Consolas:h11:cANSI
    else
        set guifont=Consolas\ 11
    endif
endif

" A buffer becomes hidden when it is abandoned
set hidden

" Specify the behavior when switching between buffers
set switchbuf=useopen,usetab

" Tab display
set showtabline=0

" Split towards the right
set splitright

" Windows fixes
if s:is_windows != 0
    set shellslash
    set isfname+=\
    set grepprg=grep\ -n
endif

" Treat long lines as break lines (useful when moving around in them)
nnoremap j gj
nnoremap k gk
" new feature
"nnoremap <silent> <expr> j (v:count == 0 ? 'gj' : 'j')
"nnoremap <silent> <expr> k (v:count == 0 ? 'gk' : 'k')

" Faster <esc>
"cmap jk <C-c> | cmap kj <C-c>
"imap jk <C-[> | imap kj <C-[>

" Console up/down/left/right navigation
cmap <C-j> <down>
cmap <C-k> <up>
cmap <C-h> <left>
cmap <C-l> <right>

" Disable search highlighting
nnoremap <silent> <C-l> <C-l>:nohlsearch<cr>

" Remap Vim 0 to first non-blank character
nmap 0 ^

" Exchange "`" and "'"
nnoremap ' `
nnoremap ` '

" Resolve inconsistency between "Y" (line), and "D" (eol)
"nmap D dd
nmap Y y$

" Visual block indenting: keep selection after indenting
vmap > >gv
vmap < <gv

" Select pasted text with gV
nmap gV `[v`]

" Replace current word
nmap <leader>r :%s/\v<<C-r><C-w>>//gc<left><left><left>

" Fast saving
nmap <silent> <leader>w :write<bar>nohlsearch<cr>

" Close this buffer
nnoremap <silent> <leader>bd :Bclose!<cr>

" Close all open buffers
nnoremap <silent> <leader>ba :BcloseAll<cr>

" Only keep this buffer open
nnoremap <silent> <leader>bo :Bonly<cr>

" Close current window
nmap <silent> <leader>q :quit<cr>

" Run "make" (makeprg or compiler)
nmap <silent> <leader>m :make<cr>

" Cd to current file
nmap <silent> <leader>cd :cd %:p:h<cr>

" In command mode, insert "%:p" when typing "%%" (very useful)
cnoremap %% <C-r>=expand("%:p")<cr>
" and remove last path component if requested
cnoremap %%<C-w> <C-r>=expand("%:p:h")<cr>/

" Newline above in insert mode
imap <S-cr> <C-o>O

" Replace forward and backward slash
nmap <leader>\ :s-/-\\-g<bar>nohlsearch<cr>
nmap <leader>/ :s-\\-/-g<bar>nohlsearch<cr>
vmap <leader>\ :s-/-\\-g<bar>nohlsearch<cr>gv
vmap <leader>/ :s-\\-/-g<bar>nohlsearch<cr>gv

" Grep the current word recursively
nmap <leader>k :grep <C-r><C-w> <C-r>=expand("%:p:h")<cr><cr>

if executable('ag') | let &grepprg = 'ag --vimgrep' | endif
if executable('rg') | let &grepprg = 'rg --vimgrep' | endif

" Toggle paste mode
nmap <silent> cop :set paste!<cr>

" Copy to clipboard
nmap <leader>y "+y
vmap <leader>y "+y

" Open alternate file
nnoremap <silent> <leader>a :buffer #<cr>

" Star/Pound the visual selection
"vmap * "vy/\M<C-r>v<cr>
"vmap # "vy?\M<C-r>v<cr>

" Toggle the quickfix window
command! -bang -nargs=? QFixToggle call ToggleQuickfixWindow()
function! ToggleQuickfixWindow()
    if exists("g:qfix_win")
        cclose
    else
        botright copen
        let g:qfix_win = bufnr('$')
    endif
endfunction
" and its mapping
nmap <silent> <leader>f :QFixToggle<cr>
" and its autocmd
augroup qfix_toggle_autocommands
    autocmd!

    autocmd WinLeave * if getbufvar(winbufnr(winnr()), '&buftype') == 'quickfix' && exists('g:qfix_win') | unlet g:qfix_win | endif
augroup END

" Clear the quickfix window
command! QFixClear call ClearQuickfixWindow()
function! ClearQuickfixWindow()
  call setqflist([])
endfunction

let g:hungarian_prefixes = ['ac', 'c', 'px', 'ppv', 'pv', 'sz', 'f', 'd', 'h', 'b']

function! ConvertHungarianNotation() range
    execute a:firstline . ',' . a:lastline
                \ . 'substitute/\v([^\w])('
                \ . join(g:hungarian_prefixes, '|')
                \ . ')([A-Z])/\1\L\3/gce'
endfunction
command! -range ConvertHungarian <line1>,<line2>call ConvertHungarianNotation()

" Add a "file" text object
onoremap af :<C-u>normal! ggVG<CR><C-o><C-o>

" Open file copied in clipboard
nmap <silent> <leader>o :edit <C-r>+<cr>
" Copy current file to clipboard
nmap <silent> <leader>p :let @+ = expand('%:p')<cr>

" CtrlP
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_map = '<leader><leader>'
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_extensions = ['tag', 'quickfix', 'line', 'mixed']
if !has('nvim')
    let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
endif

nmap <silent> <leader>j :CtrlPBuffer<cr>
nmap <silent> <leader>u :CtrlPMRUFiles<cr>

" Ack
if exists(':Ack')
    nmap <leader>k :Ack <C-r><C-w><cr>

    if executable('ag') | let g:ackprg = 'ag --vimgrep' | endif
    if executable('rg') | let g:ackprg = 'rg --vimgrep' | endif
endif

" EasyAlign
vmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" NR
"let g:nrrw_rgn_nomap_nr = 1
"let g:nrrw_rgn_nomap_Nr = 1

" Org
nnoremap <silent> <leader>n :sp ~/Bundle/org/index.org<cr>
nnoremap <silent> <leader>d :sp ~/Bundle/org/<C-r>=system('printf `date --iso-8601`')<cr>.org<cr>

" Casetrate
" "camel"  => camelCase
" "pascal" => PascalCase
" "snake"  => snake_case
" "upper"  => UPPER_CASE
" "mixed"  => Mixed_Case
let g:casetrate_leader = 'gw'

" CPP Enhanced Highlighting
let g:load_doxygen_syntax = 1
let g:cpp_class_scope_highlight = 1
"let g:cpp_experimental_template_highlight = 1

" Nerdtree
let NERDTreeRespectWildIgnore = 1
"nmap <silent> <leader>s :NERDTreeToggle<cr>

" LaTeX-specification
let g:tex_flavor = "latex"
