#!/bin/bash
#
# Configuration for bash shell colors

# Global `ls` colors
if [ -x "/usr/bin/dircolors" ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Prompt colors
NORMAL="\[\033[0m\]"
WHITE="\[\e[0;37m\]"
BLACK="\[\e[0;30m\]"
RED="\[\e[0;31m\]"
GREEN="\[\e[0;32m\]"
YELLOW="\[\e[0;33m\]"
BLUE="\[\e[0;34m\]"
PURPLE="\[\e[0;35m\]"
CYAN="\[\e[0;36m\]"
LIGHTRED="\[\e[1;31m\]"
LIGHTGREEN="\[\e[1;32m\]"
LIGHTYELLOW="\[\e[1;33m\]"
LIGHTBLUE="\[\e[1;34m\]"
LIGHTPURPLE="\[\e[1;35m\]"
LIGHTCYAN="\[\e[1;36m\]"

# Prompt format
PS1="$BLUE\u$GREEN@$WHITE\h $YELLOW\w $BLUE\$$NORMAL "
PS2="$BLUE>$NORMAL "

# vim: ft=sh et sw=2 sts=2
