#!/bin/bash
#
# Configuration for shell aliases.
#
# vim: set ft=sh

# Security
alias free="free -m"
alias df="df -h"
alias rm="rm -vi"
alias cp="cp -vi"
alias mv="mv -vi"
alias glxgears="glxgears -printfps"

# Package managing
alias install="sudo apt-get install"
alias remove="sudo apt-get remove"
alias autoremove="sudo apt-get autoremove"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade --show-upgraded"
alias clean="sudo apt-get clean"
alias search="sudo dpkg -l"

# Navigation
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias h="cd ~"
alias d="cd ~/Desktop"
alias p="cd ~/Projects"
alias b="cd ~/Bundle"
alias dw="cd ~/Downloads"
alias doc="cd ~/Documents"
alias img="cd ~/Images"
alias mkdir="mkdir -p"
alias uua="sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get autoremove -y"

# Quick display
alias grep="grep --color=auto"
alias tree="tree -Csu"
alias ls="ls -X --color=auto"
alias la="ls -A"
alias ll="ls -l"
alias lla="ls -la"

# One-key commands
alias c="clear"
alias v="vim"
alias g="gvim -f --remote-silent"
alias l="ls"
alias t="tree"
alias n="nautilus ."

# Git commands
alias got="git"
alias gut="git"
alias gco="git co"
alias gci="git ci"
alias gbr="git br"

# IF aliases
alias sshif="ssh jmcomets@iftpserv2.insa-lyon.fr"
