#!/bin/bash
#
# Configuration for shell aliases.
#
# vim: set ft=sh

# Security
alias df="df -h"
alias rm="rm -vi"
alias cp="cp -vi"
alias mv="mv -vi"

# Package managing shortcuts
alias search="sudo dpkg -l"

# Display
alias grep="grep --color=auto"
alias tree="tree -Csu"
alias ls="ls -X --color=auto"

# Shortcuts
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias p="cd ~/Projects"
alias dw="cd ~/Downloads"
alias la="ls -A"
alias ll="ls -l"
alias lla="ls -la"
alias c="clear"
alias v="vim"
alias l="ls"
alias t="tree"
alias g="gvim --remote-silent"

# Typos
alias got="git"
alias gut="git"
alias ms="ls"
alias sl="ls"
