#!/bin/bash
#
# Configuration for shell aliases.
#
# vim: set ft=sh

############### SECURITY ###############
alias free="free -m"
alias df="df -h"
alias rm="rm -vi"
alias cp="cp -vi"
alias mv="mv -vi"
alias glxgears="glxgears -printfps"
alias mkdir="mkdir -p"

############### APT-GET / DPKG ###############
alias install="sudo apt-get install"
alias remove="sudo apt-get remove"
alias autoremove="sudo apt-get autoremove"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade --show-upgraded"
alias clean="sudo apt-get clean"
alias search="sudo dpkg -l"

############### SHORCUTS ###############
alias ..="cd ../"
alias ...="cd ../../"
alias ...="cd ../../../"
alias h="history"
alias d="cd ~/Desktop"
alias p="cd ~/Projects/"
alias j="jobs -l"
alias g="gvim -f --remote-silent"
alias susu="sudo bash"
alias uua="update -y && upgrade -y && autoremove -y"

############### DISPLAY ###############
alias grep="grep --color=auto"
alias tree="tree -Csu"
alias ls="ls -X --color=auto"
alias la="ls -a"
alias ll="ls -l"
alias lla="ls -la"

