# If not running interactively, don't do anything
if [ -z "$PS1" ]; then
  return
fi

# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# Update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# Match all files and zero or more directories and subdirectories.
shopt -s globstar

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth


# Make less more friendly for non-text input files, see lesspipe(1)
if [ -x /usr/bin/lesspipe ]; then
  eval "$(SHELL=/bin/sh lesspipe)"
fi

# Set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# Launch a bash script (file) if it exists
# Usage: call f1 f2 ... fn
call()
{
    for ((j = 1 ; j <= $# ; ++j))
    do
        if [ -f "${!j}" ]; then
            . ${!j} 
        fi
    done
}

# Environment variables
export BASHRTP=~/.bash

# Global scripts
call /etc/bashrc /etc/bash_completion

# Custom scripts
call $BASHRTP/bash_colors $BASHRTP/bash_aliases $BASHRTP/bash_functions

#vim:set ft=sh
