#!/bin/bash
#
# Configuration for shell colors
#
# vim: set ft=sh

# Global `ls` color file /etc/DIR_COLORS
if [ -f "/etc/DIR_COLORS" ]; then
    eval $(dircolors -b /etc/DIR_COLORS)
fi

# Custom `ls` color file : ~/.dircolors
if [ -f "$HOME/.dircolors" ]; then
    eval $(dircolors -b ~/.dircolors)
fi

# Colors
BLACK="\[\e[0;30m\]"
BLUE="\[\e[0;34m\]"
BROWN="\[\e[0;33m\]"
CYAN="\[\e[0;36m\]"
DARKGRAY="\[\e[1;30m\]"
GREEN="\[\e[0;32m\]"
LIGHTBLUE="\[\e[1;34m\]"
LIGHTCYAN="\[\e[1;36m\]"
LIGHTGRAY="\[\e[0;37m\]"
LIGHTGREEN="\[\e[1;32m\]"
LIGHTPURPLE="\[\e[1;35m\]"
LIGHTRED="\[\e[1;31m\]"
NORMAL="\[\033[0m\]"
PURPLE="\[\e[0;35m\]"
RED="\[\e[0;31m\]"
WHITE="\[\e[1;37m\]"
YELLOW="\[\e[1;33m\]"

# Prompt format
PS1="$LIGHTBLUE\u $YELLOW\w$LIGHTPURPLE\$(__git_ps1) $LIGHTBLUE\$$NORMAL "
PS2="$LIGHTBLUE>$NORMAL "
