#!/bin/bash

# Configuration for dircolors, defining
# colors for terminal `ls` command.

# Below, there should be one TERM entry for each termtype that is colorizable
TERM ansi
TERM color_xterm
TERM color-xterm
TERM con132x25
TERM con132x30
TERM con132x43
TERM con132x60
TERM con80x25
TERM con80x28
TERM con80x30
TERM con80x43
TERM con80x50
TERM con80x60
TERM cons25
TERM console
TERM dtterm
TERM gnome
TERM kon
TERM konsole
TERM kterm
TERM linux
TERM rxvt
TERM screen
TERM screen.linux
TERM vt100
TERM xterm
TERM xterm-color

# Below are the color init strings for the basic file types. A color init
# string consists of one or more of the following numeric codes:
# Attribute codes:
# 00=none 01=bold 04=underscore 05=blink 07=reverse 08=concealed
# Text color codes:
# 30=black 31=red 32=green 33=yellow 34=blue 35=magenta 36=cyan 37=white
# Background color codes:
# 40=black 41=red 42=green 43=yellow 44=blue 45=magenta 46=cyan 47=white

# Basic system filetypes:
BLK     40;33;01 # block device driver
CHR     40;33;01 # character device driver
DIR     01;34    # directory
EXEC    01;32    # executable files
FIFO    40;33    # pipe
FILE    00       # normal file
LINK    01;36    # symbolic link
NORMAL  00       # global default, although everything should be something.
ORPHAN  40;31;01 # symlink to nonexistent file
SOCK    01;35    # socket

# DOS-style suffixes:
.bat  01;32
.btm  01;32
.cmd  01;32
.com  01;32
.exe  01;32

# Archives (bright red):
.arj  01;31
.deb  01;31
.gz   01;31
.lzh  01;31
.tar  01;31
.taz  01;31
.tgz  01;31
.z    01;31
.Z    01;31
.zip  01;31

# Images (magenta):
.avi   01;35
.bmp   01;35
.dl    01;35
.gif   01;35
.gl    01;35
.ico   01;35
.jpeg  01;35
.jpg   01;35
.mpg   01;35
.png   01;35
.ppm   01;35
.tga   01;35
.tif   01;35
.xbm   01;35
.xpm   01;35

# vim: set ft=sh
