#!/bin/bash
#
# Configuration for shell profile.
#
# vim: set ft=sh

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US" 

# Configure terminal correctly for Vi(m)
if [ -n "$DISPLAY" -a "$TERM" == "xterm" ]; then
    export TERM=xterm-256color
fi



# Vi as standard editor
export EDITOR=vi

# Add private bin directory if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
